name: Practice1
on: [push]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                node-version: 18 
            - name: Install Ci
              uses: npm ci 
            - name: Run lint
              uses: npm run lint
            - name: Run test
              uses: npm run test
            - name: Run build
              uses: npm run build
            - name: Succes
              if: success()
              run: echo "Succes ;)"
